name: Build and Deploy
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Build
        run: |
          npm install
          npm run github_page
      - name: Deploy to github page
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: html
          token: ${{ secrets.DEPLOY_TOKEN }}